<?php
// Register Custom Post Type Standort
function create_standort_mkd() {

	$labels = array(
		'name' => _x( 'Standorte', 'Post Type General Name', 'mkd-text' ),
		'singular_name' => _x( 'Standort', 'Post Type Singular Name', 'mkd-text' ),
		'menu_name' => _x( 'Standorte', 'Admin Menu text', 'mkd-text' ),
		'name_admin_bar' => _x( 'Standort', 'Add New on Toolbar', 'mkd-text' ),
		'archives' => __( 'Standort Archive', 'mkd-text' ),
		'attributes' => __( 'Standort Attribute', 'mkd-text' ),
		'parent_item_colon' => __( 'Eltern Standort:', 'mkd-text' ),
		'all_items' => __( 'Alle Standorte', 'mkd-text' ),
		'add_new_item' => __( 'Standort erstellen', 'mkd-text' ),
		'add_new' => __( 'Erstellen', 'mkd-text' ),
		'new_item' => __( 'Standort erstellen', 'mkd-text' ),
		'edit_item' => __( 'Bearbeite Standort', 'mkd-text' ),
		'update_item' => __( 'Aktualisiere Standort', 'mkd-text' ),
		'view_item' => __( 'Standort anschauen', 'mkd-text' ),
		'view_items' => __( 'Standorte anschauen', 'mkd-text' ),
		'search_items' => __( 'Suche Standort', 'mkd-text' ),
		'not_found' => __( 'Keine Standorte gefunden.', 'mkd-text' ),
		'not_found_in_trash' => __( 'Keine Standorte im Papierkorb gefunden.', 'mkd-text' ),
		'featured_image' => __( 'Beitragsbild', 'mkd-text' ),
		'set_featured_image' => __( 'Beitragsbild festlegen', 'mkd-text' ),
		'remove_featured_image' => __( 'Beitragsbild entfernen', 'mkd-text' ),
		'use_featured_image' => __( 'Als Beitragsbild verwenden', 'mkd-text' ),
		'insert_into_item' => __( 'In Standort einfügen', 'mkd-text' ),
		'uploaded_to_this_item' => __( 'Zu diesem Standort hochgeladen', 'mkd-text' ),
		'items_list' => __( 'Standorte Liste', 'mkd-text' ),
		'items_list_navigation' => __( 'Standorte Liste Navigation', 'mkd-text' ),
		'filter_items_list' => __( 'Filter Standorte Liste', 'mkd-text' ),
	);
	$args = array(
		'label' => __( 'Standort', 'mkd-text' ),
		'description' => __( '', 'mkd-text' ),
		'labels' => $labels,
		'menu_icon' => 'dashicons-admin-multisite',
		'supports' => array('title'),
		'taxonomies' => array(),
		'public' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'menu_position' => 20,
		'show_in_admin_bar' => true,
		'show_in_nav_menus' => true,
		'can_export' => true,
		'has_archive' => true,
		'hierarchical' => false,
		'exclude_from_search' => false,
		'show_in_rest' => true,
		'publicly_queryable' => false,
		'capability_type' => 'post',
	);
	register_post_type( 'mkd-locations', $args );

}
add_action( 'init', 'create_standort_mkd', 0 );


function my_remove_wp_seo_meta_box() {
	remove_meta_box('wpseo_meta', 'mkd-locations', 'normal');
}
add_action('add_meta_boxes', 'my_remove_wp_seo_meta_box', 100);


function telefon_link( $atts ) {
	$telefon_link = str_replace(" (0) ", "", $atts);
	$telefon_link = str_replace(" ", "", $telefon_link);

	return $telefon_link;
}


/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function mkd_standort_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function mkd_standort_add_meta_box() {
	add_meta_box(
		'mkd_standort-mkd-standort',
		__( 'MKD Standort', 'mkd_standort' ),
		'mkd_standort_html',
		'mkd-locations',
		'normal',
		'high'
	);
}
add_action( 'add_meta_boxes', 'mkd_standort_add_meta_box', 1 );

function mkd_standort_html( $post) {
	wp_nonce_field( '_mkd_standort_nonce', 'mkd_standort_nonce' ); ?>
	<div class="qodef-meta-box qodef-page">
	  <div class="qodef-meta-box-holder">
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Hauptsitz', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="radio" name="mkd_standort_hauptsitz" id="mkd_standort_hauptsitz_0" value="Hauptsitz" <?php echo ( mkd_standort_get_meta( 'mkd_standort_hauptsitz' )==='Hauptsitz' ) ? 'checked' : '' ; ?>> <label for="mkd_standort_hauptsitz_0">Hauptsitz</label><br>
	              <input type="radio" name="mkd_standort_hauptsitz" id="mkd_standort_hauptsitz_1" value="Niederlassung" <?php echo ( mkd_standort_get_meta( 'mkd_standort_hauptsitz' )==='Niederlassung' ) ? 'checked' : '' ; ?>> <label for="mkd_standort_hauptsitz_1">Niederlassung</label><br>
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Ansprechpartner', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_ansprechpartner" id="mkd_standort_ansprechpartner" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_ansprechpartner' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Straße', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_strasse" id="mkd_standort_strasse" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_strasse' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Hausnummer', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_hausnummer" id="mkd_standort_hausnummer" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_hausnummer' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
      <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Land', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_land" id="mkd_standort_land" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_land' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'PLZ', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_plz" id="mkd_standort_plz" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_plz' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Ort', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_ort" id="mkd_standort_ort" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_ort' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Telefon', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_telefon" id="mkd_standort_telefon" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_telefon' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Telefax', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_telefax" id="mkd_standort_telefax" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_telefax' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'E-Mail', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_e_mail" id="mkd_standort_e_mail" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_e_mail' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	    <div class="qodef-page-form-section " id="qodef_qode_seo_title">
	      <div class="qodef-field-desc">
	        <h4>
	          <?php _e( 'Maps', 'mkd-text' ); ?>
	        </h4>
	      </div>
	      <!-- close div.qodef-field-desc -->
	      <div class="qodef-section-content">
	        <div class="container-fluid">
	          <div class="row">
	            <div class="col-lg-12">
	              <input type="text" name="mkd_standort_maps" id="mkd_standort_maps" class="form-control qodef-input qodef-form-element" value="<?php echo mkd_standort_get_meta( 'mkd_standort_maps' ); ?>">
	            </div>
	          </div>
	        </div>
	      </div>
	      <!-- close div.qodef-section-content -->
	    </div>
	  </div>
	</div>

	<?php
}

function mkd_standort_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['mkd_standort_nonce'] ) || ! wp_verify_nonce( $_POST['mkd_standort_nonce'], '_mkd_standort_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['mkd_standort_hauptsitz'] ) )
		update_post_meta( $post_id, 'mkd_standort_hauptsitz', esc_attr( $_POST['mkd_standort_hauptsitz'] ) );
	if ( isset( $_POST['mkd_standort_ansprechpartner'] ) )
		update_post_meta( $post_id, 'mkd_standort_ansprechpartner', esc_attr( $_POST['mkd_standort_ansprechpartner'] ) );
	if ( isset( $_POST['mkd_standort_strasse'] ) )
		update_post_meta( $post_id, 'mkd_standort_strasse', esc_attr( $_POST['mkd_standort_strasse'] ) );
	if ( isset( $_POST['mkd_standort_hausnummer'] ) )
		update_post_meta( $post_id, 'mkd_standort_hausnummer', esc_attr( $_POST['mkd_standort_hausnummer'] ) );
	if ( isset( $_POST['mkd_standort_land'] ) )
		update_post_meta( $post_id, 'mkd_standort_land', esc_attr( $_POST['mkd_standort_land'] ) );
	if ( isset( $_POST['mkd_standort_plz'] ) )
		update_post_meta( $post_id, 'mkd_standort_plz', esc_attr( $_POST['mkd_standort_plz'] ) );
	if ( isset( $_POST['mkd_standort_ort'] ) )
		update_post_meta( $post_id, 'mkd_standort_ort', esc_attr( $_POST['mkd_standort_ort'] ) );
	if ( isset( $_POST['mkd_standort_telefon'] ) )
		update_post_meta( $post_id, 'mkd_standort_telefon', esc_attr( $_POST['mkd_standort_telefon'] ) );
	if ( isset( $_POST['mkd_standort_telefax'] ) )
		update_post_meta( $post_id, 'mkd_standort_telefax', esc_attr( $_POST['mkd_standort_telefax'] ) );
	if ( isset( $_POST['mkd_standort_e_mail'] ) )
		update_post_meta( $post_id, 'mkd_standort_e_mail', esc_attr( $_POST['mkd_standort_e_mail'] ) );
	if ( isset( $_POST['mkd_standort_maps'] ) )
		update_post_meta( $post_id, 'mkd_standort_maps', esc_attr( $_POST['mkd_standort_maps'] ) );
}
add_action( 'save_post', 'mkd_standort_save' );





/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class MKDStandorte {
	private $mkd_standorte_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'mkd_standorte_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'mkd_standorte_page_init' ) );
	}

	public function mkd_standorte_add_plugin_page() {
		add_options_page(
			'edit.php?post_type=mkd-locations',
			'MKD Standorte', // page_title
			'MKD Standorte', // menu_title
			'manage_options', // capability
			'mkd-standorte', // menu_slug
			array( $this, 'mkd_standorte_create_admin_page' ) // function
		);
	}

	public function mkd_standorte_create_admin_page() {
		$this->mkd_standorte_options = get_option( 'mkd_standorte_option_name' ); ?>

		<div class="wrap">
			<h2>MKD Standorte</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'mkd_standorte_option_group' );
					do_settings_sections( 'mkd-standorte-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function mkd_standorte_page_init() {
		register_setting(
			'mkd_standorte_option_group', // option_group
			'mkd_standorte_option_name', // option_name
			array( $this, 'mkd_standorte_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'mkd_standorte_setting_section', // id
			'Settings', // title
			array( $this, 'mkd_standorte_section_info' ), // callback
			'mkd-standorte-admin' // page
		);

		add_settings_field(
			'modus_0', // id
			'Modus', // title
			array( $this, 'modus_0_callback' ), // callback
			'mkd-standorte-admin', // page
			'mkd_standorte_setting_section' // section
		);

		add_settings_field(
			'transmitter_page_1', // id
			'Transmitter Page', // title
			array( $this, 'transmitter_page_1_callback' ), // callback
			'mkd-standorte-admin', // page
			'mkd_standorte_setting_section' // section
		);
	}

	public function mkd_standorte_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['modus_0'] ) ) {
			$sanitary_values['modus_0'] = $input['modus_0'];
		}

		if ( isset( $input['transmitter_page_1'] ) ) {
			$sanitary_values['transmitter_page_1'] = sanitize_text_field( $input['transmitter_page_1'] );
		}

		return $sanitary_values;
	}

	public function mkd_standorte_section_info() {

	}

	public function modus_0_callback() {
		?> <select name="mkd_standorte_option_name[modus_0]" id="modus_0">
			<?php $selected = (isset( $this->mkd_standorte_options['modus_0'] ) && $this->mkd_standorte_options['modus_0'] === 'Transmitter') ? 'selected' : '' ; ?>
			<option value="Transmitter" <?php echo $selected; ?>>Transmitter</option>
			<?php $selected = (isset( $this->mkd_standorte_options['modus_0'] ) && $this->mkd_standorte_options['modus_0'] === 'Receiver') ? 'selected' : '' ; ?>
			<option value="Receiver" <?php echo $selected; ?>>Receiver</option>
		</select> <?php
	}

	public function transmitter_page_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="mkd_standorte_option_name[transmitter_page_1]" id="transmitter_page_1" value="%s">',
			isset( $this->mkd_standorte_options['transmitter_page_1'] ) ? esc_attr( $this->mkd_standorte_options['transmitter_page_1']) : ''
		);
	}

}
if ( is_admin() )
	$mkd_standorte = new MKDStandorte();

/*
 * Retrieve this value with:
 * $mkd_standorte_options = get_option( 'mkd_standorte_option_name' ); // Array of All Options
 * $modus_0 = $mkd_standorte_options['modus_0']; // Modus
 * $transmitter_page_1 = $mkd_standorte_options['transmitter_page_1']; // Transmitter Page
 */












 // Create Shortcode mkd-locations_list
// Use the shortcode: [mkd-locations_list spalten="" hauptsitz="" text_align=""]
function create_mkdlocationslist_shortcode($atts) {
	// Attributes
	$atts = shortcode_atts(
		array(
			'spalten' => '',
			'hauptsitz' => '',
			'text_align' => '',
		),
		$atts,
		'mkd-locations_list'
	);
	// Attributes in var
	$spalten = $atts['spalten'];
	$hauptsitz = $atts['hauptsitz'];
	$text_align = $atts['text_align'];

	$query = new WP_Query(array(
		'post_type'		=> 'mkd-locations',
		'post_status'	=> 'publish',
		'numberposts'	=> -1,
		'order'			=> 'ASC',
		'orderby'		=> 'title'
	));


	// Output Code

	$output = '<div class="vc_row wpb_row section vc_row-fluid vc_inner" style="text-align: '.$text_align.';">';
	$output .= '<div class="full_section_inner clearfix flex-container">';

	while ($query->have_posts()) {
		$query->the_post();
		$post_id = get_the_ID();

		if($hauptsitz == get_post_meta( $post_id, "mkd_standort_hauptsitz", true))
		{
			$output .= '<div class="wpb_column vc_column_container '.$spalten.' flex-panel">';
			$output .= '<div class="vc_column-inner">';
			$output .= '<div class="wpb_wrapper">';

			$output .= '<div class="wpb_text_column wpb_content_element">';
			$output .= '<div class="wpb_wrapper">';
			$output .= '<h3>'.get_post_meta( $post_id , "mkd_standort_hauptsitz", true).' '.get_the_title($post_id).'</h3>';
			$output .= '</div>';
			$output .= '</div>';

			$output .= '<div class="vc_empty_space" style="height: 10px">';
			$output .= '<span class="vc_empty_space_inner">';
			$output .= '<span class="empty_space_image"></span>';
			$output .= '</span>';
			$output .= '</div>';

			$output .= '<div class="wpb_text_column wpb_content_element">';
			$output .= '<div class="wpb_wrapper">';
			$output .= '<p>';
			if(get_post_meta( $post_id, "mkd_standort_ansprechpartner", true) != "") {
				$output .= ''.__( 'Ihr Ansprechpartner', 'mkd-text' ).': '.get_post_meta( $post_id , "mkd_standort_ansprechpartner", true).'<br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_strasse", true) != "" && get_post_meta( $post_id, "mkd_standort_hausnummer", true) != "") {
				$output .= ''.get_post_meta( $post_id, "mkd_standort_strasse", true).' '.get_post_meta( $post_id, "mkd_standort_hausnummer", true).'<br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_land", true) != "" && get_post_meta( $post_id, "mkd_standort_plz", true) != "" && get_post_meta( $post_id, "mkd_standort_ort", true) != "") {
				$output .= ''.get_post_meta( $post_id, "mkd_standort_land", true).' - '.get_post_meta( $post_id, "mkd_standort_plz", true).' '.get_post_meta( $post_id, "mkd_standort_ort", true).'<br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_telefon", true) != "") {
				$output .= ''.__( 'Telefon', 'mkd-text' ).': <a href="tel:'.telefon_link(get_post_meta( $post_id, "mkd_standort_telefon", true)).'">'.get_post_meta( $post_id, "mkd_standort_telefon", true).'</a><br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_telefax", true) != "") {
				$output .= ''.__( 'Telefax', 'mkd-text' ).': '.get_post_meta( $post_id, "mkd_standort_telefax", true).'<br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_e_mail", true) != "") {
				$output .= ''.__( 'E-Mail', 'mkd-text' ).': <a href="'.get_post_meta( $post_id, "mkd_standort_e_mail", true).'" rel="nofollow">'.__( 'Schreiben Sie uns eine E-Mail', 'mkd-text' ).'</a><br>';
			}

			if(get_post_meta( $post_id, "mkd_standort_maps", true) != "") {
				$output .= '<a href="'.get_post_meta( $post_id, "mkd_standort_maps", true).'" target="_blank">'.__( 'Hier finden Sie uns in', 'mkd-text' ).'</a><br>';
			}
			$output .= '</p>';
			$output .= '</div>';
			$output .= '</div>';

			$output .= '<div class="vc_empty_space" style="height: 25px">';
			$output .= '<span class="vc_empty_space_inner">';
			$output .= '<span class="empty_space_image"></span>';
			$output .= '</span>';
			$output .= '</div>';

			$output .= '</div>';
			$output .= '</div>';
			$output .= '</div>';
		}
	}
	$output .= '</div>';
	$output .= '</div>';

	/*
		Usage: mkd_standort_get_meta( 'mkd_standort_hauptsitz' )
		Usage: mkd_standort_get_meta( 'mkd_standort_ansprechpartner' )
		Usage: mkd_standort_get_meta( 'mkd_standort_strasse' )
		Usage: mkd_standort_get_meta( 'mkd_standort_hausnummer' )
		Usage: mkd_standort_get_meta( 'mkd_standort_land' )
		Usage: mkd_standort_get_meta( 'mkd_standort_plz' )
		Usage: mkd_standort_get_meta( 'mkd_standort_ort' )
		Usage: mkd_standort_get_meta( 'mkd_standort_telefon' )
		Usage: mkd_standort_get_meta( 'mkd_standort_telefax' )
		Usage: mkd_standort_get_meta( 'mkd_standort_e_mail' )
		Usage: mkd_standort_get_meta( 'mkd_standort_maps' )
	*/


	return $output;
}
add_shortcode( 'mkd-locations_list', 'create_mkdlocationslist_shortcode' );

// Create Standorte element for Visual Composer
add_action( 'vc_before_init', 'mkdlocationslist_integrateWithVC' );
function mkdlocationslist_integrateWithVC() {
	vc_map( array(
		'name' => __( 'Standorte', 'mkd-text' ),
		'base' => 'mkd-locations_list',
		'icon' => plugins_url( 'images/favicon.jpg', dirname(__FILE__) ),
		'show_settings_on_create' => true,
		'category' => __( 'MK Design', 'mkd-text'),
		'params' => array(
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'admin_label' => false,
				'heading' => __( 'Spalten', 'mkd-text' ),
				'param_name' => 'spalten',
				'value' => array(
					'Bitte wählen' => '',
					'1 Spalten' => 'vc_col-sm-12',
          '2 Spalten' => 'vc_col-sm-6',
					'3 Spalten' => 'vc_col-sm-4',
          '4 Spalten' => 'vc_col-sm-3',
				),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'admin_label' => false,
				'heading' => __( 'Hauptsitz', 'mkd-text' ),
				'param_name' => 'hauptsitz',
				'value' => array(
					'Bitte wählen' => '',
					'Hauptsitz' => 'Hauptsitz',
					'Niederlassung' => 'Niederlassung',
				),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'admin_label' => false,
				'heading' => __( 'Text Align', 'mkd-text' ),
				'param_name' => 'text_align',
				'value' => array(
					'Bitte wählen' => '',
					'Left' => 'left',
          'Center' => 'center',
          'Right' => 'right',
				),
			),
		)
	) );
}
